name: ui
description: Shared UI components, Dhivehi localization, and Theme.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^6.1.0 # For Mapbox offline caching
  latlong2: ^0.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
