HEAD
name: dhivashi_mobile
description: Dhivashi mobile app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

name: dhivashi_root
description: Root workspace placeholder
publish_to: 'none'
environment:
  sdk: '>=3.0.0 <4.0.0'
 d682691 (commit)
